// Static symbol bank for dynamic context-word tiles. Mirrors backend/src/context/symbols.py 1:1
// (backend/tests/test_symbols.py enforces the sync) -- ids are lucide-react export names in
// kebab-case. Unknown/missing ids render no symbol (tolerant by design): a tile is always usable
// by its word alone, the symbol is a bonus, never a requirement.
import {
  Backpack,
  BookOpen,
  NotebookPen,
  Pencil,
  Eraser,
  Scissors,
  Ruler,
  Calculator,
  ClipboardList,
  FileText,
  Laptop,
  Table,
  Clock,
  FlaskConical,
  Beaker,
  TestTube,
  Microscope,
  Magnet,
  Battery,
  Cable,
  Plug,
  Zap,
  Lightbulb,
  Thermometer,
  Scale,
  Rocket,
  Globe,
  Sun,
  Cloud,
  CloudRain,
  Snowflake,
  Droplets,
  Flame,
  Leaf,
  Flower,
  TreePine,
  Cat,
  Dog,
  Bug,
  Rabbit,
  Palette,
  Paintbrush,
  Shapes,
  Puzzle,
  Blocks,
  Camera,
  Music,
  Guitar,
  Mic,
  Headphones,
  Hammer,
  Wrench,
  Box,
  Package,
  Recycle,
  Building,
  Apple,
  Banana,
  Carrot,
  Pizza,
  Sandwich,
  Cookie,
  CakeSlice,
  CupSoda,
  GlassWater,
  Utensils,
  IceCreamCone,
  House,
  Bus,
  Car,
  Shirt,
  Bed,
  Gift,
  Coins,
  ShoppingCart,
  Phone,
  Users,
  Hand,
  Heart,
  Star,
  Trophy,
  PartyPopper,
  Gamepad2,
  Volleyball,
  Bandage,
  TriangleAlert,
  Smile,
  Frown,
  Angry,
  Laugh,
  Meh,
  type LucideIcon,
} from 'lucide-react'

export const SYMBOL_ICONS: Record<string, LucideIcon> = {
  'backpack': Backpack,
  'book-open': BookOpen,
  'notebook-pen': NotebookPen,
  'pencil': Pencil,
  'eraser': Eraser,
  'scissors': Scissors,
  'ruler': Ruler,
  'calculator': Calculator,
  'clipboard-list': ClipboardList,
  'file-text': FileText,
  'laptop': Laptop,
  'table': Table,
  'clock': Clock,
  'flask-conical': FlaskConical,
  'beaker': Beaker,
  'test-tube': TestTube,
  'microscope': Microscope,
  'magnet': Magnet,
  'battery': Battery,
  'cable': Cable,
  'plug': Plug,
  'zap': Zap,
  'lightbulb': Lightbulb,
  'thermometer': Thermometer,
  'scale': Scale,
  'rocket': Rocket,
  'globe': Globe,
  'sun': Sun,
  'cloud': Cloud,
  'cloud-rain': CloudRain,
  'snowflake': Snowflake,
  'droplets': Droplets,
  'flame': Flame,
  'leaf': Leaf,
  'flower': Flower,
  'tree-pine': TreePine,
  'cat': Cat,
  'dog': Dog,
  'bug': Bug,
  'rabbit': Rabbit,
  'palette': Palette,
  'paintbrush': Paintbrush,
  'shapes': Shapes,
  'puzzle': Puzzle,
  'blocks': Blocks,
  'camera': Camera,
  'music': Music,
  'guitar': Guitar,
  'mic': Mic,
  'headphones': Headphones,
  'hammer': Hammer,
  'wrench': Wrench,
  'box': Box,
  'package': Package,
  'recycle': Recycle,
  'building': Building,
  'apple': Apple,
  'banana': Banana,
  'carrot': Carrot,
  'pizza': Pizza,
  'sandwich': Sandwich,
  'cookie': Cookie,
  'cake-slice': CakeSlice,
  'cup-soda': CupSoda,
  'glass-water': GlassWater,
  'utensils': Utensils,
  'ice-cream-cone': IceCreamCone,
  'house': House,
  'bus': Bus,
  'car': Car,
  'shirt': Shirt,
  'bed': Bed,
  'gift': Gift,
  'coins': Coins,
  'shopping-cart': ShoppingCart,
  'phone': Phone,
  'users': Users,
  'hand': Hand,
  'heart': Heart,
  'star': Star,
  'trophy': Trophy,
  'party-popper': PartyPopper,
  'gamepad-2': Gamepad2,
  'volleyball': Volleyball,
  'bandage': Bandage,
  'triangle-alert': TriangleAlert,
  'smile': Smile,
  'frown': Frown,
  'angry': Angry,
  'laugh': Laugh,
  'meh': Meh,
}

export function symbolIcon(id?: string): LucideIcon | null {
  if (!id) return null
  return SYMBOL_ICONS[id] ?? null
}
